[package]
name = "molecules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mlc"
path = "src/lib.rs"

[[bin]]
name = "contestant"
path = "tests/con_test.rs"

[dependencies]
